### ISSUE TITLE
Update to latest version on Pop!_OS 21.10

### ISSUE THREAD

**Issue by JoseExposito** [pop-os/touchegg#3] opened 2021-11-02 16:52 UTC
@andirsun reported this [issue originally](https://github.com/JoseExposito/gnome-shell-extension-x11gestures/issues/29) in the companion GNOME Shell X11 Gestures extension.

libinput 1.18 introduced a [breaking change](https://gitlab.freedesktop.org/libinput/libinput/-/commit/60d5172e15728cc25db889a7a6bcf37a06a15a3a) in the way deltas are reported.

The change is already [handled](https://github.com/JoseExposito/touchegg/commit/541b4b51f17d783a5becf19075c713f85cb67542) upstream in 2.0.10. 

Updating the package is required to avoid issues on Pop!_OS 21.10.

**Comment by andirsun** [comment] 2021-11-05 15:07
@JoseExposito the version was updated in last build, so the problem is fixed. 
You can close the issue.

**Comment by jackpot51** [comment] 2021-11-05 15:33
Yeah, we have version 2.0.12 now

**Closed as completed** 2021-11-05 15:33 UTC
