### ISSUE TITLE
Four-finger left-swipe not working on fresh Pop!_OS install with version 2.0.15

### ISSUE THREAD

**Issue by XV-02** [pop-os/touchegg#11] opened 2023-01-24 01:13 UTC
### The Issue

After a clean install with Pop!_OS 22.04 Intel iso 21, and subsequently completing a full upgrade of packages, four-finger left-swipe no longer functions.

### Background in case other users think they might have this problem
In Pop!_OS multitouch trackpad gestures are supported. In Cosmic for Gnome, Pop!_OS utilizes three finger gestures for quickly moving window focus as part of it's less directly mouse-driven design (swiping fingers is faster than moving a cursor discretely and clicking). The general direction of the sweep is used to allow focus to be thrown quickly through windows. 

Along side three-finger gestures, Pop!_OS uses four-finger interactions to access some of the shell features including switching between workspaces, and deploying the Workspace and Application Views. 

Pop!_OS' inclination to making individual UX elements more mono-functional means that the Applications View and Workspaces View are separated. By default, a four-finger right-swipe will bring up the Applications View and a subsequent left- or right- swipe will dismiss the view. For Workspaces View, the left-swipe is used. Up and Down switch between logically adjacent workspaces.

### Is this my problem?

If four-finger left-swipes, which bring up the Workspaces View, don't work for you this **_may_** be your issue. You can run `touchegg --debug` in a terminal and check if your output matches below.

### Logs

When attempting a four-finger left-swipe, `touchegg --debug` yields the following:
```
Gesture begin detected
               Gesture information:
                              Fingers: 4
                              Type: SWIPE
                              Direction: LEFT
               Gesture performed on app: Gjs
               Action configured for this gesture
               Ignoring this gesture. This could mean no action is configured, the configured action is not 
               supported or that it was performed in a system window (panel, dock, desktop, etc)
```

Doing the same to the right provides constant output indicating `Gesture update detected ({some number}%)`

### Other notes:

On a much older Pop!_OS install (updated from 21.10, and regularly since), updating did not break the four-finger left-swipe gesture. Restarting Touchegg did not remedy the issue either. The problem didn't present until after rebooting following the update (as far as I could tell).

**Comment by n3m0-22** [comment] 2023-01-24 01:33
A little over a year ago I had a one off I was never able to replicate where installing [touche](https://github.com/JoseExposito/touche) broke 4 finger swipe. It was fixed by finding the broken swipe in touche (workspaces view in this case) and setting the option in the dropdown to `Execute a command`. I remember this as I just checked to see if it would happen when testing #10 the other day. I was not able to reproduce it then either, but it may be a helpful place to start investigating.

**Comment by XV-02** [comment] 2023-01-24 18:32
This issue was cropping up on at least 3 fresh installs. Each one was installed from the recent general release ISO (21), and then fully updated. 

The part that gets me is that older installs seemed fine. I would expect that to apply to our ISO as well, seeing as https://github.com/pop-os/touchegg/pull/10 isn't baked into the most recent general release. And, the swipe works on a fresh install prior to bringing everything up to date, or when touchegg is held. 

So far, it's been seen on a Lemp9, a Lemp6, and a DevOne. 

I did note that the same debug text which appeared for four-finger left-swipe also appeared for  up- and down-, even though those inputs work.

**Comment by thomas-zimmerman** [comment] 2023-01-25 22:30
In working with HP they have started seeing user reports that some of the gestures are not working. Looking requested logs, I'm seeing this:

```
Jan 25 14:31:39 hpdevone gnome-shell[466732]: ../../../gobject/gsignal.c:2765: instance '0x55bc1ee256d0' has no handler with id '1'
Jan 25 14:31:39 hpdevone gnome-shell[466732]: ../../../gobject/gsignal.c:2765: instance '0x55bc1ee256d0' has no handler with id '2'
Jan 25 14:31:39 hpdevone gnome-shell[466732]: Source ID 3511065 was not found when attempting to remove it
Jan 25 14:31:39 hpdevone gnome-shell[466732]: Source ID 3518006 was not found when attempting to remove it
Jan 25 14:31:39 hpdevone gnome-shell[466732]: Source ID 3510680 was not found when attempting to remove it
Jan 25 14:31:39 hpdevone gnome-shell[466732]: [popx11gestures@system76.com] Extension disabled
Jan 25 14:31:39 hpdevone gnome-shell[466732]: [popx11gestures@system76.com] Building entry point for GNOME Shell 42.3.1
Jan 25 14:31:39 hpdevone gnome-shell[466732]: [popx11gestures@system76.com] No tracker, skipping
Jan 25 14:31:39 hpdevone gnome-shell[466732]: [VERTICAL-OVERVIEW] resetting overrides
Jan 25 14:31:39 hpdevone gnome-shell[466732]: [VERTICAL-OVERVIEW] disabled
Jan 25 14:31:39 hpdevone gnome-shell[466732]: [popx11gestures@system76.com] Connection with Touchégg daemon lost: null
Jan 25 14:31:39 hpdevone gnome-shell[466732]: [popx11gestures@system76.com] Connection manually closed, not reconnecting to the daemon
```
The direct report that this error message is from has these gestures not working:

* Application library
* Pinch to zoom
* Workspace overview
* Switching Windows

**Closed as completed** 2023-01-26 00:03 UTC

**Comment by jacobgkau** [comment] 2023-01-26 00:06
@thomas-zimmerman I tested #12 on a Dev One and was only able to recreate left four-finger swipe breaking without the fix (it works with the fix.) Right four-finger swipe continued working even without the fix.

The issue you're describing may be something different, so let us know if it still occurs once version [2e20838](https://github.com/pop-os/touchegg/commit/2e20838f2065a0a5e4da08c211bd6edcfb1ba705) is released and people have that installed.

**Comment by thomas-zimmerman** [comment] 2023-01-26 18:44
Sounds like the 4 finger swipe is fixed but at least one HP customer is still seeing other gestures that are not working.
